#!/bin/sh
#
# Load modules related to TS-7180
#

umask 077

start() {
	printf "Loading modules for TS-7180 peripherals: "
	modprobe wilc3000
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
